OWN-SIZE/Server

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/closetController.ts
ownsize-express/src/controller/index.ts
ownsize-express/src/index.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/router/index.ts
ownsize-express/src/service/closetService.ts
ownsize-express/src/service/index.ts

전체 옷장 조회 기능 테스트까지 완료했으니깐 로컬에서 확인해 줘!
확인 완료해서 코드리뷰 달아주면, develop 브랜치로 머지할건데 
이렇게 기능 하나 끝낼 때마다 develop에 머지하고,  작업 시작할때마다 develop 브랜치 pull부터  땡겨준 다음 시작하면 될거야

[ADD] 전체 옷장 조회

---

ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/closetController.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/closetService.ts

Related to: #5
- 전체 옷장 의류 정보 삭제 
- 로컬 테스트 완료

[ADD] 전체 옷장 의류 정보 삭제

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/closetController.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/closetService.ts

Related to: #3
- 전체 옷장 조회 시 각 유저별로 전체 옷장 조회 가능하도록 수정
- 로컬 테스트 완료

[FIX]전체옷장 조회 필터 수정

---

ownsize-express/package-lock.json
ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/response.ts
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/closetController.ts
ownsize-express/src/controller/index.ts
ownsize-express/src/controller/sizeController.ts
ownsize-express/src/router/index.ts
ownsize-express/src/router/sizeRouter.ts
ownsize-express/src/service/index.ts
ownsize-express/src/service/sizeService.ts

Related to: #15 
- 내 하의 사이즈 정보 입력받아 MySize 테이블에 저장
- 로컬 테스트 완료
브랜치 12에서 이어서 15를 만들었는데 (develop에서 안파고 12에서 이어서 했다는 말)
15 구현하고 12에서 수정사항이 있어서 12로 브랜치 이동해서 push 했더니 12에 15꺼 같이 다 올라감^^
결론 : 12랑 15랑 PR 내용 같음. 참고바람요

[ADD] 내 하의 사이즈 정보 입력

---

ownsize-express/src/index.ts

[FIX]포트번호 변경

---

ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/categoryController.ts
ownsize-express/src/index.ts
ownsize-express/src/router/categoryRouter.ts
ownsize-express/src/service/categoryService.ts

Related to: #11
- 카테고리 내 의류 삭제
- 로컬 테스트 완료

[ADD] 카테고리 내 의류 삭제

---

ownsize-express/package-lock.json
ownsize-express/package.json
ownsize-express/src/index.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/yarn.lock

[ADD] CORS 설정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/categoryController.ts
ownsize-express/src/controller/closetController.ts
ownsize-express/src/router/categoryRouter.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/categoryService.ts
ownsize-express/src/service/closetService.ts

Related to: #34
- 카테고리에 의류 추가 
- 로컬 테스트 완료
- 중계 테이블에 추가한다 생각하고 접근하면 이해 쉬움

[ADD] 전체옷장 변수명 변경&카테고리에 의류추가 기능

---

ownsize-express/package-lock.json
ownsize-express/package.json
ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/pageController.ts
ownsize-express/src/index.ts
ownsize-express/src/service/pageService.ts
ownsize-express/yarn.lock

Related to: #18 
- 마이페이지 조회시 유저의 프로필 이미지까지 응답해주도록 코드 수정
- DB 도 변경해놓음
- 로컬 테스트 완료

[FEAT] 유저이미지 DB, response 코드 추가

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/categoryController.ts
ownsize-express/src/controller/extensionController.ts
ownsize-express/src/router/extensionRouter.ts
ownsize-express/src/router/index.ts
ownsize-express/src/service/extensionService.ts
ownsize-express/src/service/index.ts
ownsize-express/src/service/pageService.ts

Related to: #22
- 전체옷장에 저장
- 토큰  유저인증 부분은 소셜로그인 완성시 추가 예정
- body에 userId 추가 시 로컬 테스트 성공

[ADD] 전체옷장에 저장(미완)

---

ownsize-express/src/controller/closetController.ts

Related to: #4
- isPin 조건처리 수정
- 로컬 테스트 완료

[FIX] isPin 조건처리 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/sizeController.ts
ownsize-express/src/service/sizeService.ts

Related to: #14 
-  상의 사이즈 정보 입력시 단면, 둘레 구분 추가
- 로컬 테스트 완료

[FIX] 상의 사이즈 정보 입력시 단면, 둘레 구분 추가

---

ownsize-express/src/controller/sizeController.ts
ownsize-express/src/service/sizeService.ts

Related to: #15 
- 하의 사이즈 입력시 단면, 둘레 구분 추가
- response status 변경
- 로컬 테스트 완료

[FIX] 하의 사이즈 입력시 단면, 둘레 구분 추가

---

ownsize-express/src/router/pageRouter.ts
ownsize-express/src/service/closetService.ts

Related to: #18 
- 마이페이지 라우트 path 변경
- 로컬 테스트 완료

[FIX] 마이페이지 라우트 path 변경

---

ownsize-express/src/controller/extensionController.ts
ownsize-express/src/service/extensionService.ts

[FIX] db 테이블 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/extensionController.ts
ownsize-express/src/service/extensionService.ts

[FIX] 비교 사이즈 수동입력 시 컬럼순서 구분하여 저장

---

ownsize-express/src/controller/extensionController.ts
ownsize-express/src/router/extensionRouter.ts
ownsize-express/src/service/extensionService.ts
ownsize-express/src/service/pageService.ts

Related to: #19 
Related to: #22 
- 전체옷장 저장시 isRecommend true면 Recommend 테이블 내용 추가
- 사이즈 추천 기록 조회시 Recommend 테이블에서 사이즈 null이면 - 으로 변경
- 로컬테스트 완료
기존의 전체옷장 저장시, userId 값 설정이 not null이어서 req.body 에 받아서 써야할 듯
[Recommend 테이블에서 사이즈 null이면 - 으로 변경] 관련 코드(PageService.ts)에서는 null인 모든 값 변경 방식으로 구현(updateMany)

[ADD] 전체옷장 저장시 Rec테이블 추가, 사이즈 추천 기록 조회 수정

---

ownsize-express/src/service/categoryService.ts

Related to: #8 
- 카테고리 삭제 안되는 오류 수정
- 로컬테스트 완료
AllCloset_Category 테이블에서 categoryId 를 참조하고 있어서 Category 테이블 삭제시 AllCloset_Category에 있는 값을 먼저 삭제해줘야함

[FIX] 카테고리 삭제 오류 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/extensionController.ts
ownsize-express/src/router/extensionRouter.ts
ownsize-express/src/service/extensionService.ts

Related to: #21
- 사이즈 추천 알고리즘을 통해 추천받은 사이즈를 DB에 저장
- 로컬 테스트 완료

[ADD] 사이즈 추천 결과 저장

---

ownsize-express/package-lock.json
ownsize-express/src/service/closetService.ts
ownsize-express/yarn.lock

[FIX] 중계 테이블에서부터 삭제 추가

---

ownsize-express/src/controller/categoryController.ts
ownsize-express/src/service/categoryService.ts
ownsize-express/src/service/closetService.ts

Related to: #57
- 카테고리 핀 기능 추가
- 로컬 테스트 완료

[FIX] 카테고리 핀 기능 추가

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/service/extensionService.ts

[FIX] db 수정

---

ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/extensionController.ts
ownsize-express/src/router/extensionRouter.ts
ownsize-express/src/service/extensionService.ts

Related to: #74
- 크롤링한 사이즈표 저장 (사이즈별 정보 한 요청에 한 list)
-  로컬 테스트 완료

[ADD] 크롤링한 사이즈표 저장

---

ownsize-express/src/controller/closetController.ts
ownsize-express/src/index.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/closetService.ts

[FEAT] allCloset 조회 유저인증, cors에러

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/closetController.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/closetService.ts

[FEAT] closetRouter 유저인증 코드 수정 완료

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/closetController.ts
ownsize-express/src/index.ts
ownsize-express/src/router/closetRouter.ts
ownsize-express/src/service/closetService.ts

closetRouter 완료

---

ownsize-express/.gitignore
ownsize-express/package.json
ownsize-express/src/index.ts
ownsize-express/yarn.lock

[ADD] https 배포

---

ownsize-express/src/controller/closetController.ts
ownsize-express/src/middlewares/auth.ts
ownsize-express/src/service/categoryService.ts
ownsize-express/src/service/closetService.ts

[FEAT] 전체옷장 정보 수정 요소 추가&카테고리 상세조회  isInPin 같이조회

---

ownsize-express/src/service/categoryService.ts

[FEAT] 코드수정

---

README.md
ownsize-express/src/service/extensionService.ts

[FIX] 하의 사이즈 추천 예외처리

---

ownsize-express/src/index.ts

[FIX] 포트번호 수정

---

ownsize-express/src/service/authService.ts
ownsize-express/src/service/sizeService.ts

[FIX] 마이사이즈 입력 코드 수정

---

ownsize-express/src/service/authService.ts
ownsize-express/src/service/sizeService.ts

[FIX] 마이사이즈 코드 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/sizeController.ts
ownsize-express/src/index.ts
ownsize-express/src/router/sizeRouter.ts
ownsize-express/src/service/sizeService.ts

Related to: #
- 마이페이지 내에서 상의와 하의 정보 수정
- 로컬테스트 완료 
put API로 update 코드 작성함

마이페이지 내에서 상의, 하의 정보 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/constants/responseMessage.ts
ownsize-express/src/controller/userController.ts
ownsize-express/src/router/userRouter.ts
ownsize-express/src/service/userService.ts

[ADD] 이메일 수집 & 수집한 이메일 조회

---

ownsize-express/src/service/categoryService.ts

Related to: #
-  해당 카테고리 이름 데이터셋에 추가
- 로컬 테스트 완료

[FIX] 카테고리 상세 조회 코드 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/sizeController.ts

mySize 소수 입력

---

ownsize-express/src/service/extensionService.ts

Related to: #21
- 사이즈추천 NaN 결과값 예외처리
- 로컬 테스트 완료

[FIX] 사이즈추천 NaN 결과값 예외처리

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/authController.ts
ownsize-express/src/service/authService.ts
ownsize-express/src/service/pageService.ts

Related to: #
- picture(프로필 사진) 구글 로그인시 웹에게 전달받고 디비에 저장
- 마이페이지 조회시 response로 보내줌
- 로컬테스트 안했음

회원가입 및 로그인시 프로필 사진 저장, 마이페이지 조회 응답

---

ownsize-express/src/service/categoryService.ts

Related to: #10
- 핀 고정 최신순 정렬(카테고리 내부)
-

[FIX] 핀 고정 최신순 정렬(카테고리 내부)

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/controller/sizeController.ts
ownsize-express/src/service/authService.ts
ownsize-express/src/service/sizeService.ts

Related to: #
- isAlreadyUser 상태 반영 분기처리
- 사이즈 입력 시에 클라단에서 상태 전송 / 로그인할때만 서버단에서 상태 업데이트
- 로컬 테스트 완료

[FEAT] isAlreadyUser 상태 반영 분기처리

---

ownsize-express/src/controller/extensionController.ts
ownsize-express/src/service/extensionService.ts

[FIX] isManual속성 제거

---

ownsize-express/src/controller/authController.ts
ownsize-express/src/service/authService.ts

Related to: #
- 바보같이 디비 삭제하는 순서만 맞춰 놓고 코드 제대로 안짬
-

[FIX] 탈퇴 코드 수정

---

ownsize-express/prisma/schema.prisma
ownsize-express/src/service/authService.ts

Related to: #
- refresh token 유효기간 없앰
-

token 유효기간 변경

---

ownsize-express/src/service/extensionService.ts

Related to: #21 
- 크롤링 데이터 중복 수정
- 로컬 테스트 완료

[FIX] 크롤링 데이터 중복 수정

---

ownsize-express/src/service/extensionService.ts

Related to: #21
- 상의 사이즈 추천 예외처리
- 로컬 테스트 완료

[FIX] 상의 사이즈 추천 예외처리
